apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-codegen-secret-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/test-codegen-secret-2:0b792dfc32e06e2eea614d3992820069f6591cca@sha256:a276ca5d603fc0ce0962c2a6ba6566c12bdd38de8a9f23f61aea6ad15e8be741 # use pre-built to bootstrap 
          name: app-inference
